name: Check PR title

on:
    pull_request_target:
        types: [ opened, edited, synchronize ]

jobs:
    check_pr_title:
        name: 'Check PR title'
        runs-on: ubuntu-latest
        steps:
            -   uses: amannn/action-semantic-pull-request@v4.5.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
